window.IFM_ACTIVITY_CATALOG = {
  groups: [
    ["hero",      "Hero Deneyimler"],
    ["arrival",   "Premium Karşılama"],
    ["immersive", "Mekan Enstalasyonları"],
    ["moving",    "Hareketli Performanslar"]
  ],
  activities: [
    {
      id: "A01",
      group: "hero",
      scenario: ["tech"],
      tier: "Signature",
      media: "Uluslararası",
      title: "Drone Işık Gösterisi",
      short: "IFM logosunu İstanbul semasında tek karelik, güçlü bir final imzasına dönüştürür.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A01-drone-light-show.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=kv0PT2ftFiM"],
      summary: "Gece finalinde oynatılan ana dış mekan gösterisidir. Drone sürüsü kısa bir müzik kurgusuyla IFM logosu ve finans temasını gökyüzünde kurar.",
      ifm: "Dış plaza veya görüş açısı uygun bir çevre noktasında kurulur.",
      visitor: "Net, kısa ve prestijli bir kapanış anı üretir.",
      media_ops: "SHGM izinleri, rüzgar limiti ve kalabalık yönetimi kritik başlıklardır.",
      ops: "SHGM izinleri, rüzgar limiti ve kalabalık yönetimi kritik başlıklardır."
    },
    {
      id: "A02",
      group: "hero",
      scenario: ["finale"],
      tier: "Signature",
      media: "Uluslararası",
      title: "Kurdele Tetikli Cephe Mapping",
      short: "Kurdele kesimiyle birlikte cephe, ışık ve müzik devreye girer; açılış anı görünür olur.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A02-projection-mapping-ribbon.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=o85tfZ049bM"],
      summary: "Klasik kurdele kesimini görsel bir açılış cue'suna dönüştürür. Kesim anı ile mapping, ışık ve müzik aynı saniyede devreye girer.",
      ifm: "Cephe, atrium duvarı veya ana LED yüzey seçilir. Kurdele anı timecode ile tetiklenir.",
      visitor: "Açılışın başladığı saniye herkes tarafından net algılanır.",
      ops: "Mapping yüzeyi, projeksiyon mesafesi, parlaklık ve protokol cue yönetimi prova ile netleştirilmelidir."
    },
    {
      id: "A03",
      group: "hero",
      scenario: ["tech"],
      tier: "Signature",
      media: "Uluslararası",
      title: "Kinetik Işık Orkestrası",
      short: "Atrium tavanındaki hareketli ışık objeleri, mekana ritim, derinlik ve tören ölçeği kazandırır.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A03-kinetic-light-orchestra.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=b5LMY1RjGbs"],
      summary: "Açılışın iç mekandaki ana show parçasıdır. Tavana yerleşen motorize ışık modülleri müzikle senkron hareket eder.",
      ifm: "Atrium veya yüksek tavan aksında uygulanır. VIP açılışta ana blok olarak oynatılır.",
      visitor: "Mekânın ölçeği ve mimari derinliği yeni bir boyut kazanır.",
      ops: "Rigging hesabı, motor güvenliği, DMX kontrolü ve tavan yük taşıma onayı gerekir."
    },
    {
      id: "A04",
      group: "hero",
      scenario: ["finale"],
      tier: "Signature",
      media: "Uluslararası",
      title: "Uluslararası İmza Performans",
      short: "Yurtdışından getirilecek özel ekip, geceye tek ve prestijli bir ana sahne anı ekler.",
      impact: "Çok yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A04-aerial-performance.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=ZrFx-pr5PmA"],
      summary: "Uluslararası performans beklentisine doğrudan cevap verir. Aerial, çağdaş dans veya teknoloji destekli sahne işi olarak seçilebilir.",
      ifm: "VIP açılış akışında 6-10 dakikalık ana sahne momenti olarak konumlanır.",
      visitor: "Gerçekten özel booking ile gelmiş bir performans izlendiği hissi yaratır.",
      ops: "Booking, rider, seyahat, prova ve rigging hattı ikinci fazda netleşir."
    },
    {
      id: "A05",
      group: "hero",
      scenario: ["tech"],
      tier: "Premium",
      media: "Ulusal",
      title: "Holografik Açılış Sunucusu",
      short: "Fiziksel sunucuya eşlik eden holografik host, protokol akışına akıllı bir teknoloji katmanı katar.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A05-holographic-host.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=I0XQXe9uNxY"],
      summary: "Sunum akışına teknoloji katmanı ekler. Holografik host açılış mesajı verir ve sahne geçişlerini destekler.",
      ifm: "Ana sahnede holo gauze veya LED fan tekniğiyle uygulanır.",
      visitor: "Klasik sunucu akışından farklı bir giriş ve geçiş deneyimi yaratır.",
      ops: "Sahne ışık kontrolü, açı yönetimi ve önceden hazırlanan metin gerekir."
    },
    {
      id: "A06",
      group: "hero",
      scenario: ["arrival"],
      tier: "Signature",
      media: "Uluslararası",
      title: "Mimari Lazer Gösterisi",
      short: "Cephe ve kule hatlarını lazerle okuyarak mapping veya drone finaline güçlü bir gece geçişi kurar.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A06-architectural-laser.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=KE89-HOdEKY"],
      summary: "Bina mimarisini lazerle okunur hale getirir. Mapping ya da drone finaline köprü görevi görür.",
      ifm: "Dış cephe, plaza ve karşı bina aksları kullanılarak çok noktadan kurulur.",
      visitor: "Yapının kendisinin show'un parçası haline geldiğini görür.",
      ops: "Lazer güvenliği, beam yönleri, sis desteği ve resmi güvenlik prosedürleri gerekir."
    },
    {
      id: "A07",
      group: "arrival",
      scenario: ["arrival"],
      tier: "Premium",
      media: "Yerel",
      title: "Aynalı VIP Giriş Tüneli",
      short: "VIP girişi aynalı yüzeyler, ışık ve kontrollü akışla fotojenik bir karşılama hattına dönüşür.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A07-mirror-arrival-tunnel.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=8VwJMw_fLvI"],
      summary: "VIP girişini sıradan karşılama alanından çıkarır. Misafirler ışıklı ve aynalı bir geçişten yürüyerek ana alana alınır.",
      ifm: "Giriş aksında 12-20 metrelik modüler bir tünel olarak kurulabilir.",
      visitor: "İçeri girmeden önce özel bir davet hissi oluşur.",
      ops: "Sirkülasyon genişliği, yangın çıkışı ve fotoğraf aksı planlanmalıdır."
    },
    {
      id: "A08",
      group: "arrival",
      scenario: ["tech"],
      tier: "Deneyim",
      media: "Yerel",
      title: "İnteraktif Projeksiyon Zemini",
      short: "Davetlinin adımına tepki veren zemin, geçiş alanını yaşayan bir medya yüzeyine çevirir.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A08-interactive-floor.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=dRG25nRGOnY"],
      summary: "Zemin yüzeyini davetlinin hareketine tepki veren medya alanına dönüştürür. Adım atıldıkça ışık izi, dalga ya da marka motifi belirir.",
      ifm: "Atrium girişi ya da geniş koridor aksında çalıştırılır.",
      visitor: "Kendi hareketine tepki veren bir mekan görür. Telefonla çekmeye çok uygundur.",
      ops: "Projeksiyon yüksekliği, sensör kalibrasyonu ve zemin kaymazlığı kontrol edilir."
    },
    {
      id: "A09",
      group: "arrival",
      scenario: [],
      tier: "Premium",
      media: "Yerel",
      title: "Volumetrik Hologram İstasyonu",
      short: "Logo, mimari form veya açılış mesajını üç boyutlu algıyla gösteren premium deneyim noktası.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A09-volumetric-hologram.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=d6MCG3S5DIA"],
      summary: "Misafirin kısa süre durup izlediği holografik bir deneyim noktasıdır. IFM maketi veya açılış mesajı burada gösterilebilir.",
      ifm: "VIP girişte ya da protokol çevresinde konumlanır.",
      visitor: "Holografik objeyi etrafından izler, kısa video çeker ve etkinlik alanına geçer.",
      ops: "Cihaz güvenliği, karanlık kontrolü ve içerik renderı doğru çözülmelidir."
    },
    {
      id: "A10",
      group: "arrival",
      scenario: [],
      tier: "Premium",
      media: "Ulusal",
      title: "Projeksiyon Karşılama Portalı",
      short: "VIP geçiş aksını ışık ve mapping ile çerçeveleyen, ilk temas anını büyüten karşılama eşiği.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A10-projection-portal.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=W3B9N4Zr5xQ"],
      summary: "Misafirin geçtiği kapıyı kendi başına bir show unsuruna dönüştürür. Portal yüzeyi ışık ve içerikle canlı hale gelir.",
      ifm: "VIP girişte ya da plaza içine yönelen ana aks üzerinde konumlanır.",
      visitor: "İlk geçiş noktasında etkinliğin ölçeğini hisseder.",
      ops: "Portal taşıyıcısı, içerik cue'su ve kalabalık akışı aynı plan içinde çözülmelidir."
    },
    {
      id: "A11",
      group: "arrival",
      scenario: [],
      tier: "Deneyim",
      media: "Yerel",
      title: "Holografik Karşılama Totemi",
      short: "Giriş hattında logo, mesaj ve yönlendirmeyi hareketli holografik obje diliyle sunar.",
      impact: "Orta-Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A11-holographic-totem.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=E6r7mvXLnMw"],
      summary: "Giriş aksına fiziksel signage yerine teknolojik bir karşılama objesi yerleştirir. Marka mesajı, logo veya yönlendirme burada verilir.",
      ifm: "Protokol girişi, lounge yakını ya da plaza girişinde konumlanır.",
      visitor: "Statik pano yerine canlı, ışıklı ve daha prestijli bir obje görür.",
      ops: "Gün ışığı, ekran açısı ve enerji beslemesi dikkate alınmalıdır."
    },
    {
      id: "A12",
      group: "arrival",
      scenario: ["arrival"],
      tier: "Deneyim",
      media: "Ulusal",
      title: "Işık Peçe Koridoru",
      short: "Dikey ışık ve hafif sis, davetliyi sakin, lüks ve sinematik bir geçiş atmosferine alır.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A12-light-veil-corridor.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=v3lIyGFpcuc"],
      summary: "Arrival deneyimini daha sakin ve lüks bir çizgiye taşır. Sert tünel yerine daha hafif, hava gibi bir ışık koridoru kurulur.",
      ifm: "VIP yürüyüş rotasında veya mağaza koridorunda kurulur.",
      visitor: "Yürürken ışığın içinden geçiyormuş hissi alır.",
      ops: "Sis yoğunluğu, klima etkisi ve yangın alarmı uyumu dikkat ister."
    },
    {
      id: "A13",
      group: "immersive",
      scenario: [],
      tier: "Premium",
      media: "Ulusal",
      title: "Dijital Nehir Akışı",
      short: "Zemin boyunca akan medya içeriği, plaza ve iç akslarda yaşayan bir açılış rotası kurar.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A13-digital-river.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=-5im9Uh2hJg"],
      summary: "IFM içinde ya da dış plazada akış hissi veren dijital bir rota kurar. Projeksiyon, ışık ve ses aynı kurguya bağlanır.",
      ifm: "Geniş yürüyüş aksı veya plaza zemini seçilir.",
      visitor: "Dijital akışın içinden veya yanından yürür. Dekor değil, mekanın parçası gibi algılanır.",
      ops: "Parlaklık, projeksiyon yüzeyi ve yürüme güvenliği beraber düşünülmelidir."
    },
    {
      id: "A14",
      group: "immersive",
      scenario: [],
      tier: "Premium",
      media: "Ulusal",
      title: "İnteraktif Işık Ormanı",
      short: "Harekete tepki veren ışık çubukları, geçiş alanını fotojenik ve yaşayan bir enstalasyona çevirir.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A14-light-forest.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=8Nj2O60BJdk"],
      summary: "Misafirin içinden geçebildiği veya kenarından yürüdüğü ışıklı bir enstalasyon alanı kurar. Dikey çizgiler yumuşak tepki verir.",
      ifm: "Atrium kenarı veya geniş koridor hattında modüler sistem olarak kurulur.",
      visitor: "Yürüdükçe ışıklar canlanır. Influencer yürüyüş çekimleri için uygundur.",
      ops: "Elektrik dağıtımı, sabitleme ve yangın geçiş boşlukları çözülmelidir."
    },
    {
      id: "A15",
      group: "immersive",
      scenario: ["arrival"],
      tier: "Premium",
      media: "Uluslararası",
      title: "Kinetik Heykel Plaza",
      short: "Yavaş hareket eden kinetik obje, açılış alanına sanat eseri niteliğinde kalıcı bir odak verir.",
      impact: "Yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A15-kinetic-sculpture.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=Pb4lUd2zO3w"],
      summary: "Açılış alanına hareket eden bir sanat objesi yerleştirir. Gösteri gibi değil, mekanın imza parçası gibi çalışır.",
      ifm: "Atrium boşluğu veya dış plaza merkezinde güvenli mesafe ile kurulur.",
      visitor: "Objenin yanında durur, izler ve fotoğraf çeker. Üst segment bir deneyim hissi verir.",
      ops: "Mühendislik hesabı, mekanik güvenlik ve bakım erişimi gerekir."
    },
    {
      id: "A16",
      group: "immersive",
      scenario: [],
      tier: "Premium",
      media: "Ulusal",
      title: "Su Perdesi Projeksiyonu",
      short: "Su veya sis perdesinde beliren görüntü, açılış mesajını fiziksel olmayan etkileyici bir yüzeye taşır.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A16-water-screen.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=mSnMGw462Vk"],
      summary: "Klasik LED yerine su veya sis yüzeyinde görüntü gösterir. Açılış mesajı fiziksel olmayan bir yüzeyde belirir.",
      ifm: "Dış alanda su perdesi, iç mekanda daha kontrollü bir sis ekranı olarak kurgulanabilir.",
      visitor: "Görüntünün havada asılıymış gibi belirdiğini görür.",
      ops: "Rüzgar, drenaj, nem ve zemin korunması birlikte çözülmelidir."
    },
    {
      id: "A17",
      group: "immersive",
      scenario: [],
      tier: "Premium",
      media: "Ulusal",
      title: "Askılı Işık Bulutu",
      short: "Atrium tavanında yüzen ışık kümeleri, mekana gün boyu yaşayan zarif bir odak kazandırır.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A17-suspended-light-cloud.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=cYCvDcNb2Nk"],
      summary: "Atriuma kalıcıya yakın bir değer katar. Tavanda yüzen ışık kümeleri gün içinde de yaşayabilir.",
      ifm: "Tavan taşıyıcısı uygun olan atrium veya geniş iç boşlukta kurulur.",
      visitor: "Show anı dışında da etkileyici bir mekan objesi görür.",
      ops: "Rigging, bakım erişimi ve yangın güvenliği onayı gerekir."
    },
    {
      id: "A18",
      group: "immersive",
      scenario: ["tech"],
      tier: "Premium",
      media: "Ulusal",
      title: "Generatif Medya Sanat Duvarı",
      short: "Büyük yüzey, veri, ışık ve ritimle çalışan çağdaş bir medya sanat işine dönüşür.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A18-media-art-wall.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=ghQpl1V4Zeg"],
      summary: "Büyük bir duvarı açılış için yaşayan sanat yüzeyine çevirir. İçerik veri akışı, ışık ve ritim üzerinden ilerler.",
      ifm: "Mağaza cephesi, medya duvarı veya büyük geçiş duvarında uygulanır.",
      visitor: "Tek noktada durup izleyebileceği güçlü bir dijital sanat yüzeyi görür.",
      ops: "İçerik üretim süresi, ekran/projeksiyon çözünürlüğü ve loop yönetimi dikkate alınmalıdır."
    },
    {
      id: "A19",
      group: "moving",
      scenario: [],
      tier: "Deneyim",
      media: "Yerel",
      title: "LED Işık Geçidi",
      short: "LED kostümlü ekip, AVM içinde gezen ve kalabalığı programa taşıyan canlı bir performans akışı yaratır.",
      impact: "Orta-Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A19-light-parade.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=n2UOg67p9LM"],
      summary: "Sabit sahne dışında AVM içine yayılan performans üretir. Ekip belirli saatlerde rota yürür ve kısa durak show'ları yapar.",
      ifm: "Atrium, mağaza koridorları ve dış plaza arasında rotalar planlanır.",
      visitor: "Beklemediği anda canlı bir performansla karşılaşır.",
      ops: "Rota genişliği, güvenlik eşliği ve kostüm bataryası planı gerekir."
    },
    {
      id: "A20",
      group: "moving",
      scenario: ["arrival"],
      tier: "Deneyim",
      media: "Yerel",
      title: "LED Dans Performansı",
      short: "Programlanabilir LED kostümlerle kısa, enerjik ve yüksek paylaşım potansiyelli bir sahne anı üretir.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A20-led-dancers.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=IR84C6ah6vc"],
      summary: "4-8 dansçıyla yapılan ışıklı koreografi performansıdır. Müzik ve kostüm ışıkları aynı kurguda çalışır.",
      ifm: "Kurdele sonrası, DJ öncesi veya kısa yükseltici blok olarak kullanılabilir.",
      visitor: "Hızlı ve enerjik bir sahne anı izler. Telefonla çekmeye çok uygundur.",
      ops: "Koreografi provası, batarya yönetimi ve sahne zemini planı gerekir."
    },
    {
      id: "A21",
      group: "moving",
      scenario: ["finale"],
      tier: "Signature",
      media: "Uluslararası",
      title: "Havada Orkestra / Uçan Müzisyenler",
      short: "Canlı müzik ve aerial sahneleme, gecenin en zarif ve yukarı baktıran performans anını kurar.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A21-flying-musicians.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=Bc0VO8sq8dw"],
      summary: "Canlı müzik ile aerial performansı bir araya getirir. Müzisyen veya solist yukarıda sahnelenir ve çok özel bir an yaratır.",
      ifm: "Atrium yüksekliği uygunsa gerçek askı sistemiyle, değilse yükseltilmiş platform versiyonla uygulanabilir.",
      visitor: "Mekana yukarıdan yayılan müzik ve performansı izler. Gösteri zarif ve VIP kitleye uygun kalır.",
      ops: "Rigging mühendisliği, sigorta, prova ve sanatçı güvenliği kritik konulardır."
    },
    {
      id: "A22",
      group: "moving",
      scenario: [],
      tier: "Deneyim",
      media: "Yerel",
      title: "LED Perküsyon Geçidi",
      short: "LED vurmalı çalgılarla gezen ritim ekibi, alanı ses, ışık ve hareketle canlı tutar.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A22-led-percussion.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=5CwAXpEi6tA"],
      summary: "Klasik bando yerine daha çağdaş ve görsel bir ritim kurgusu sunar. LED vurmalı ekibi yürüyüş ve durak performanslarını birleştirir.",
      ifm: "Giriş alanı, plaza ve atrium hattında hareketli akış yaratmak için uygundur.",
      visitor: "Ritmi hem duyar hem görür. Enerjiyi yükseltirken AVM içinde yönlendirme de yapar.",
      ops: "Ses seviyesi, rota güvenliği ve kısa set planı hazırlanmalıdır."
    },
    {
      id: "A23",
      group: "moving",
      scenario: ["finale"],
      tier: "Signature",
      media: "Ulusal",
      title: "Senkron LED Bileklik Finali",
      short: "Senkron LED bileklikler, seçili davetlileri final gösterisinin görünür bir parçası yapar.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A23-wristband-finale.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=lqZT095bAz0"],
      summary: "Finali izleyen seçili kitleyi gösterinin parçası yapar. Bileklikler müzik ve sahne cue'suyla senkron yanar.",
      ifm: "VIP alanı veya finale davet edilen izleyici grubunda uygulanır.",
      visitor: "Sadece izleyen değil, finale katılan kişinin parçası olur.",
      ops: "Bileklik dağıtımı, toplama planı ve senkron kontrolü gerekir."
    },
    {
      id: "A24",
      group: "moving",
      scenario: [],
      tier: "Deneyim",
      media: "Yerel",
      title: "Lazer Arp Performansı",
      short: "Lazer tellerle çalınan canlı performans, müzik ve ışığı tek bir sahne anında birleştirir.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A24-laser-harp.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=euytMaRh8HM"],
      summary: "Canlı performans ile lazer görselliğini tek show içinde birleştirir. Kısa sahne segmenti olarak güçlü bir fark yaratır.",
      ifm: "Ana sahne, atrium demo alanı veya gala akışında kısa blok olarak kullanılabilir.",
      visitor: "Hem müzikal hem görsel olarak dikkat çeken bir performans izler.",
      ops: "Lazer güvenliği, sahne açısı ve sis yoğunluğu dikkatle yönetilmelidir."
    }
  ]
};
