window.IFM_ACTIVITY_CATALOG = {
  groups: [
    ["hero", "Hero Experiences"],
    ["arrival", "Premium Arrival Experiences"],
    ["immersive", "Immersive Installations"],
    ["moving", "Moving Performances"]
  ],
  activities: [
    {
      id: "A01",
      group: "hero",
      title: "Drone Light Show",
      short: "Açılış finalinde İFM ve İstanbul temasını gökyüzünde anlatan koreografili drone gösterisi.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/concepts/concept-07-drone.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=kv0PT2ftFiM"],
      summary: "Bu aktivite, açılışın dış alanda görülebilen ana final gösterisidir. Drone sürüsü; İFM silüeti, İstanbul bağlantıları ve final mesajını kısa bir koreografiyle gökyüzünde gösterir.",
      ifm: "İFM dış plaza veya görüş açısı uygun bir çevre noktası izleyici alanı olarak planlanır. Drone gösterisi, laser ve kısa müzik kurgusuyla birlikte gece finaline yerleştirilir.",
      visitor: "Konuklar gösteriyi telefonla rahatça çekebilecekleri açık bir alana yönlendirilir. Gösteri 8-12 dakika arasında tutulur; tempo yüksek, mesaj net olur.",
      media: "Basın ve influencer için en güçlü geniş açı görüntüyü üretir. Havadan ve yerden çekilecek resmi kayıt, etkinlik sonrası PR filminde ana kapanış görüntüsü olur.",
      ops: "SHGM izinleri, uçuş güvenlik koridoru, rüzgar limiti, yedek tarih ve kalabalık güvenliği baştan planlanmalıdır."
    },
    {
      id: "A02",
      group: "hero",
      title: "Kurdele Tetikli Projection Mapping",
      short: "Kurdele kesildiği anda cephe, LED ekran veya atrium yüzeyinde başlayan mapping ve ışık anı.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/concepts/concept-06-mapping.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=o85tfZ049bM"],
      summary: "Bu aktivite, klasik kurdele kesimini görsel bir açılış anına dönüştürür. Protokol kurdeleyi kestiğinde eş zamanlı olarak mapping, ışık ve müzik sistemi devreye girer.",
      ifm: "İFM cephesi, atrium duvarı veya ana LED ekran yüzeyi mapping için seçilir. Kurdele anı timecode ile tetiklenir; ışık önce kesim noktasından başlar, sonra mekan geneline yayılır.",
      visitor: "Davetli, kurdele anının sadece protokol fotoğrafı olmadığını görür. Kesimden hemen sonra mekanda gerçek bir açılış hissi oluşur.",
      media: "Basın için net bir fotoğraf ve kısa video anı üretir. Kurdele, yönetim ve ışık patlaması aynı karede yakalanabilir.",
      ops: "Mapping yüzeyi, projeksiyon mesafesi, parlaklık, ses sistemi, prova saati ve protokol cue yönetimi netleştirilmelidir."
    },
    {
      id: "A03",
      group: "hero",
      title: "Ana Açılış Kinetik Işık Gösterisi",
      short: "Atriumda motorize ışık objeleri ve müzikle çalışan programlanmış ana show.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/concepts/concept-05-kinetic-light.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=b5LMY1RjGbs"],
      summary: "Bu aktivite, açılışın iç mekandaki ana ışık gösterisidir. Tavana veya sahne üstüne yerleşen motorize ışık elemanları müzikle senkron şekilde hareket eder.",
      ifm: "İFM atrium veya geniş tavan aksında uygulanır. Show, VIP açılış saatinde ana program parçası olarak oynatılır; açılış sonrası kısa günlük gösteriye dönüştürülebilir.",
      visitor: "Konuk yukarıda hareket eden ışık objelerini izlerken mekanın ölçeğini hisseder. Gösteri kısa, yoğun ve izlenebilir bir formatta tutulur.",
      media: "Dikey video, geniş açı ve drone olmayan iç mekan çekimleri için güçlü bir içerik üretir. Mekanın mimari değerini artırarak gösterir.",
      ops: "Rigging hesabı, motor güvenliği, bakım erişimi, DMX/timecode kontrolü ve yangın/güvenlik onayları gerekir."
    },
    {
      id: "A04",
      group: "hero",
      title: "International Signature Performance",
      short: "Yurtdışından getirilecek aerial, teknoloji-dans veya ışık performansının ana sahne gösterisi.",
      impact: "Çok yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/concepts/concept-09-aerial.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=ZrFx-pr5PmA"],
      summary: "Bu aktivite, müşterinin istediği uluslararası performans beklentisine karşılık gelen ana sahne işidir. Aerial, çağdaş dans, ışık kostümü veya teknoloji destekli performans olarak seçilebilir.",
      ifm: "VIP programda 6-10 dakikalık özel bir gösteri olarak konumlanır. Sahne arkasında LED/mapping içerik kullanılarak performans İFM görsel kimliğine bağlanır.",
      visitor: "Davetli, standart konser öncesi show değil, özel olarak getirilmiş ve sahnelenmiş bir performans izler.",
      media: "Cemiyet ve influencer kitlesi için paylaşılabilir kısa sahne anı üretir. Uluslararası ekip kullanımı basın metninde somut bir değer olarak yazılabilir.",
      ops: "Sanatçı booking, uçuş/konaklama, teknik rider, sahne yüksekliği, rigging ve prova takvimi ikinci fazda netleşmelidir."
    },
    {
      id: "A05",
      group: "hero",
      title: "Holographic Opening Host",
      short: "Fiziksel sunucuya sahnede kısa süre eşlik eden holografik host veya dijital anlatıcı.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/concepts/concept-08-hologram.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=I0XQXe9uNxY"],
      summary: "Bu aktivite, açılış sunumuna teknoloji katmanı ekler. Holografik host; açılış mesajını verir, fiziksel sunucuya bağlanır ve program geçişlerini kısa bloklarla destekler.",
      ifm: "Ana sahnede LED fan, holo-gauze veya Pepper's Ghost benzeri teknikle uygulanır. İçerik 60-90 saniyelik bölümler halinde hazırlanır.",
      visitor: "Konuk, klasik sunucu akışı yerine teknolojiyle desteklenmiş, daha dikkat çekici bir sahne geçişi görür.",
      media: "Holografik host, sosyal medyada kısa klip olarak çalışır. Basın metninde teknoloji destekli açılış unsuru olarak somut şekilde anlatılır.",
      ops: "Sahne ışık kontrolü, görüntü açısı, önceden hazırlanmış konuşma metni, seslendirme ve teknik failover gerekir."
    },
    {
      id: "A06",
      group: "arrival",
      title: "Mirror Arrival Tunnel",
      short: "VIP girişinde aynalı yüzey, ışık çizgisi ve fotoğraf açısıyla kurulan premium karşılama tüneli.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/concepts/concept-15-light-route.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=8VwJMw_fLvI"],
      summary: "Bu aktivite, VIP girişini sıradan karşılama alanı olmaktan çıkarır. Davetliler aynalı ve ışıklı kısa bir geçişten yürüyerek ana etkinlik alanına alınır.",
      ifm: "Giriş aksında 12-20 metrelik modüler tünel kurulabilir. Ayna, koyu metal, çizgisel LED ve düşük yoğunluklu sisle kurumsal bir atmosfer oluşturulur.",
      visitor: "Davetli mekana girmeden önce premium bir geçiş deneyimi yaşar. Tünel çıkışında kontrollü fotoğraf ve basın karşılama noktası yer alır.",
      media: "Kırmızı halı yerine daha modern ve fotojenik bir arrival görüntüsü üretir. Influencer içerikleri için ilk temas noktası olur.",
      ops: "Sirkülasyon genişliği, yangın çıkışı, zemin kaymazlığı, kamera açısı ve güvenlik personeli planlanmalıdır."
    },
    {
      id: "A07",
      group: "arrival",
      title: "Interactive Projection Floor",
      short: "Giriş veya atrium zemininde yürüdükçe tepki veren projection floor deneyimi.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/concepts/concept-02-projection-floor.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=dRG25nRGOnY"],
      summary: "Bu aktivite, zemin yüzeyini davetlilerin hareketine tepki veren bir medya alanına dönüştürür. Yürüyen kişinin arkasında ışık izi, dalga veya marka motifi oluşur.",
      ifm: "Atriuma giriş aksı, geniş koridor veya VIP yönlendirme rotasında uygulanır. Tasarım İFM renkleri ve mimari çizgileriyle sade tutulur.",
      visitor: "Konuk yürürken mekanın onun hareketine tepki verdiğini görür. Deneyim basit, anlaşılır ve video çekmeye uygundur.",
      media: "Üstten çekim ve telefon videoları için etkili çalışır. Kalabalığın akışını görsel olarak canlı gösterir.",
      ops: "Projeksiyon yüksekliği, ışık seviyesi, sensör kalibrasyonu, kablo güvenliği ve zemin kaymazlığı kontrol edilmelidir."
    },
    {
      id: "A08",
      group: "arrival",
      title: "Volumetric Hologram Experience",
      short: "VIP alanda ürün, mimari veya mesajı üç boyutlu holografik görüntüyle gösteren deneyim noktası.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/concepts/concept-08-hologram.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=d6MCG3S5DIA"],
      summary: "Bu aktivite, konukların kısa süre durup izleyebileceği holografik bir deneyim alanıdır. Sunucu host'tan farklı olarak sürekli çalışır ve bilgi/deneyim noktası gibi kullanılır.",
      ifm: "VIP giriş veya lounge yakınında, İFM maketi, açılış mesajı ya da seçili kiracı temalarını gösteren volumetrik ekran kurulabilir.",
      visitor: "Konuk holografik objeyi etrafından izler, kısa videoya alır ve etkinlik alanına geçer. Deneyim 20-30 saniyede anlaşılır.",
      media: "Teknoloji algısını destekleyen net bir yakın plan içerik verir. Basın turunda gösterilecek kontrollü bir demo noktası olur.",
      ops: "Ekran tekniği, karanlık kontrolü, içerik dosyası, yoğunluk yönetimi ve cihaz güvenliği planlanmalıdır."
    },
    {
      id: "A09",
      group: "immersive",
      title: "Digital River Flows",
      short: "Zemin, duvar veya su öğesi üzerinde akan dijital nehir projection deneyimi.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/concepts/concept-04-water-screen.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=-5im9Uh2hJg"],
      summary: "Bu aktivite, İFM içinde veya dış plazada akış hissi veren bir dijital nehir görüntüsü kurar. Projection, ışık, ses ve mümkünse ince sis/su efektiyle çalışır.",
      ifm: "Geniş bir yürüyüş aksı veya plaza zemini seçilir. İçerik İstanbul'un su bağlantısı ve finans akışı fikrini doğrudan anlaşılır görsellerle taşır.",
      visitor: "Konuk dijital nehir hattının üzerinden veya yanından yürür. Deneyim bir dekor değil, mekanın içinden geçen bir rota gibi algılanır.",
      media: "Hareketli zemin görüntüsü sosyal medyada iyi çalışır. Etkinlik filminde mekan geçişlerini bağlayan güçlü bir ara görüntü verir.",
      ops: "Projeksiyon yüzeyi, parlaklık, yürüyüş güvenliği, sis/su etkisi ve teknik ekipman koruması gerektirir."
    },
    {
      id: "A10",
      group: "immersive",
      title: "Interactive Light Forest",
      short: "Atrium veya koridorda konuk geçişine tepki veren dikey ışık çubukları ve ses tasarımı.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/concepts/concept-03-sound-sculpture.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=8Nj2O60BJdk"],
      summary: "Bu aktivite, konukların içinden geçebileceği ışıklı bir enstalasyon alanıdır. Dikey LED çubukları veya ince ışık kolonları hareket algılayarak tepki verir.",
      ifm: "Geniş bir koridor veya atrium kenarında 20-40 metrelik bir geçiş hattı kurulabilir. Tasarım kalabalık akışını bozmayacak şekilde seyrek ve zarif tutulur.",
      visitor: "Konuk alandan geçerken ışıklar yavaşça yanar, renk değiştirir veya sesle birlikte hareket eder. Deneyim hızlı anlaşılır ve fotojeniktir.",
      media: "Düşük ışıkta premium görüntü verir. Influencer ve basın için kontrollü yürüyüş çekimi üretir.",
      ops: "Elektrik dağıtımı, sensör kalibrasyonu, zemine sabitleme, yangın geçişleri ve gece bakım kontrolü gerekir."
    },
    {
      id: "A11",
      group: "immersive",
      title: "Kinetic Sculpture Plaza",
      short: "Dış plaza veya atriumda hareket eden metal/ışık heykeliyle kurulan imza enstalasyon.",
      impact: "Yüksek",
      difficulty: "Yüksek",
      image: "assets/concepts/concept-14-robotic.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=8-hxsm8lDps"],
      summary: "Bu aktivite, açılış alanına hareket eden bir sanat objesi yerleştirir. Kinetik heykel ışıkla birlikte yavaş hareket eder ve mekanın imza fotoğraf noktasına dönüşür.",
      ifm: "Dış plaza veya ana atrium boşluğunda güvenli mesafeyle kurulur. Açılış saatinde özel koreografi, gün içinde daha sakin hareket modu çalışır.",
      visitor: "Konuk heykelin yanında durur, izler ve fotoğraf çeker. Deneyim bağıran bir show değil, premium bir mekan objesi gibi çalışır.",
      media: "Mimarlık, tasarım ve etkinlik medyası için güçlü bir görsel değer üretir. Etkinliğe sanat objesi niteliği katar.",
      ops: "Mühendislik hesabı, mekanik güvenlik, elektrik, bakım erişimi, çevre bariyeri ve sigorta planı gerekir."
    },
    {
      id: "A12",
      group: "immersive",
      title: "Water Screen Projection",
      short: "Su perdesi veya sis ekranı üzerine video, ışık ve lazer görüntüsü yansıtılan gösteri.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/concepts/concept-04-water-screen.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=mSnMGw462Vk"],
      summary: "Bu aktivite, görüntüyü klasik LED ekran yerine su veya sis yüzeyinde gösterir. Açılış mesajı, logo veya kısa film havada asılıymış gibi algılanır.",
      ifm: "Dış alanda rüzgar kontrolü uygunsa su perdesi, iç mekanda daha kontrollü bir sis ekranı kullanılabilir. Kısa gösteri veya geçiş noktası olarak çalışır.",
      visitor: "Konuk görüntünün fiziksel bir ekranda değil, su/sis yüzeyinde belirdiğini görür. Deneyim 1-3 dakikalık kısa bloklarla sunulur.",
      media: "Yakın plan video ve ağır çekim çekimler için güçlüdür. Basın dilinde 'su perdesi projection' olarak net anlatılabilir.",
      ops: "Rüzgar, drenaj, nem, projeksiyon parlaklığı, lazer güvenliği ve çevre zemininin korunması önemlidir."
    },
    {
      id: "A13",
      group: "moving",
      title: "Light Parade",
      short: "AVM içinde belirlenmiş rotada gezen LED kostümlü performans ekibi.",
      impact: "Orta-Yüksek",
      difficulty: "Orta",
      image: "assets/concepts/concept-11-led-dance.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=n2UOg67p9LM"],
      summary: "Bu aktivite, sabit sahne dışında AVM içine yayılan hareketli performans yaratır. LED kostümlü ekip belirli saatlerde dolaşır ve kısa durak performansları yapar.",
      ifm: "Atrium, mağaza koridorları ve dış plaza arasında 15-20 dakikalık rotalar planlanır. Performans, kalabalığı ana gösteri alanına yönlendirmek için kullanılabilir.",
      visitor: "Konuk performansla beklemediği anda karşılaşır. Fotoğraf çekebilir, ekibi takip ederek ana alana yönlenebilir.",
      media: "Sosyal hikaye içerikleri için sürekli hareketli malzeme üretir. Mekanın farklı noktalarının görünmesini sağlar.",
      ops: "Rota genişliği, güvenlik eşliği, kostüm batarya süresi, müzik seviyesi ve kalabalık yönetimi planlanmalıdır."
    },
    {
      id: "A14",
      group: "moving",
      title: "LED Dancers",
      short: "Programlanabilir LED kostümlerle yapılan kısa koreografili dans performansı.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/concepts/concept-11-led-dance.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=IR84C6ah6vc"],
      summary: "Bu aktivite, sahne veya atrium içinde 4-8 dansçıyla yapılan ışıklı koreografi performansıdır. Kostümler müzik ve sahne ışığıyla senkron çalışır.",
      ifm: "Ana programda kurdele sonrası veya DJ öncesi kısa bir yükseltici bölüm olarak kullanılabilir. LED kostüm renkleri İFM görsel diliyle programlanır.",
      visitor: "Konuk hızlı, anlaşılır ve enerjik bir görsel performans izler. Performans ayakta izlemeye ve telefonla çekmeye uygundur.",
      media: "Kısa reels ve story formatına çok uygundur. Açılış filminde dinamik ara sekans olarak kullanılabilir.",
      ops: "Koreografi provası, kostüm bataryaları, kablosuz kontrol, sahne zemini ve dansçı kulis alanı gerekir."
    },
    {
      id: "A15",
      group: "moving",
      title: "Flying Musicians / Floating Orchestra",
      short: "Canlı müzisyenlerin aerial performansla birlikte yukarıda veya askıda sahnelendiği özel gösteri.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/concepts/concept-10-symphonic.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=Bc0VO8sq8dw"],
      summary: "Bu aktivite, canlı müzik ile aerial performansı birleştirir. Müzisyen, solist veya performansçı belirli yükseklikte sahnelenerek açılış için özel bir gösteri anı yaratır.",
      ifm: "Atrium tavan yüksekliği uygunsa aerial rigging ile uygulanır. Alternatif olarak yükseltilmiş platform ve ışık tasarımıyla daha düşük riskli versiyon yapılabilir.",
      visitor: "Konuk, mekana yukarıdan yayılan canlı müziği ve performansı izler. Gösteri kısa, zarif ve VIP kitleye uygun tutulur.",
      media: "İç mekanda güçlü bir 'tek kare' üretir. Basın için canlı müzik, aerial performans ve mimariyi aynı görüntüde birleştirir.",
      ops: "Rigging mühendisliği, sanatçı güvenliği, sigorta, prova, tavan yüksekliği ve acil durum planı kritik başlıklardır."
    }
  ]
};
