window.IFM_ACTIVITY_CATALOG = {
  groups: [
    ["hero", "Hero Experiences"],
    ["arrival", "Premium Arrival Experiences"],
    ["immersive", "Immersive Installations"],
    ["moving", "Moving Performances"]
  ],
  activities: [
    {
      id: "A01",
      group: "hero",
      title: "Drone Light Show",
      short: "Açılış finalinde IFM AVM logosunu ve İstanbul silüetini gökyüzünde kuran koreografili drone gösterisi.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A01-drone-light-show.png",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=kv0PT2ftFiM"],
      summary: "Bu aktivite gece finalinde oynatılan ana dış mekan gösterisidir. Drone sürüsü kısa bir müzik kurgusuyla IFM AVM logosu, finans teması ve final mesajını gökyüzünde kurar.",
      ifm: "Dış plaza veya görüş açısı uygun bir çevre noktasında kurulur. İzleyici alanı, resmi çekim aksı ve güvenlik çeperi baştan tanımlanır.",
      visitor: "Misafirler gösteriyi tek noktadan rahat izler ve telefonla kayıt alır. Net, kısa ve prestijli bir kapanış anı üretir.",
      media: "Basın ve influencer için en güçlü geniş açı görüntülerden birini verir. Resmi aftermovie'de ana kapanış karesi olur.",
      ops: "SHGM izinleri, rüzgar limiti, uçuş güvenlik koridoru, yedek tarih ve kalabalık yönetimi kritik başlıklardır."
    },
    {
      id: "A02",
      group: "hero",
      title: "Kurdele Tetikli Projection Mapping",
      short: "Kurdele kesildiği anda cephede veya atrium yüzeyinde başlayan mapping ve ışık tetikleme anı.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A02-ribbon-mapping.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=o85tfZ049bM"],
      summary: "Bu aktivite klasik kurdele kesimini görsel bir açılış cue'suna dönüştürür. Kesim anı ile mapping, ışık ve müzik aynı saniyede devreye girer.",
      ifm: "Cephe, atrium duvarı veya ana LED yüzey seçilir. Kurdele anı timecode ile tetiklenir ve ışık kesim noktasından mekana yayılır.",
      visitor: "Davetli sadece protokol fotoğrafı değil gerçek bir açılış anı görür. Açılışın başladığı saniye herkes tarafından net algılanır.",
      media: "Kurdele, yönetim ve görsel patlama aynı karede birleşir. Basın için kolay anlatılan bir başlama anı yaratır.",
      ops: "Mapping yüzeyi, projeksiyon mesafesi, parlaklık, ses sistemi ve protokol cue yönetimi prova ile netleştirilmelidir."
    },
    {
      id: "A03",
      group: "hero",
      title: "Ana Açılış Kinetik Işık Orkestrası",
      short: "Atrium tavanında motorize ışık elemanları ve müzikle çalışan ana iç mekan gösterisi.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A03-kinetic-light.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=b5LMY1RjGbs"],
      summary: "Bu aktivite açılışın iç mekandaki ana show parçasıdır. Tavana yerleşen motorize ışık modülleri müzikle senkron hareket eder.",
      ifm: "Atrium veya yüksek tavan aksında uygulanır. VIP açılışta ana blok olarak oynatılır, sonrasında kısa gösteri moduna dönebilir.",
      visitor: "Misafir yukarıdaki hareketli ışık objelerini izlerken mekanın ölçeğini hisseder. Gösteri kısa ama yoğun tutulur.",
      media: "İç mekanda çok güçlü dikey video ve geniş açı görüntü üretir. Mimariyi de daha etkileyici gösterir.",
      ops: "Rigging hesabı, motor güvenliği, DMX kontrolü, bakım erişimi ve tavan yük taşıma onayı gerekir."
    },
    {
      id: "A04",
      group: "hero",
      title: "International Signature Performance",
      short: "Yurtdışından getirilecek aerial, teknoloji-dans veya ışık temelli sahne performansı.",
      impact: "Çok yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A04-signature-performance.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=ZrFx-pr5PmA"],
      summary: "Bu aktivite müşterinin talep ettiği uluslararası performans beklentisine doğrudan cevap verir. Aerial, çağdaş dans veya teknoloji destekli sahne işi olarak seçilebilir.",
      ifm: "VIP açılış akışında 6-10 dakikalık bir ana sahne momenti olarak konumlanır. Arka planda IFM'ye özel içerik çalıştırılır.",
      visitor: "Misafir standart dans gösterisi değil, gerçekten özel booking ile gelmiş bir performans izlediğini hisseder.",
      media: "Cemiyet, influencer ve basın için kısa paylaşılabilir sahne anları üretir. Uluslararası ekip vurgusu haber değerini yükseltir.",
      ops: "Booking, rider, seyahat, prova, sahne yüksekliği ve gerekiyorsa rigging hattı ikinci fazda netleşir."
    },
    {
      id: "A05",
      group: "hero",
      title: "Holographic Opening Host",
      short: "Fiziksel sunucuya sahnede eşlik eden holografik host veya dijital anlatıcı.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A05-holographic-host.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=I0XQXe9uNxY"],
      summary: "Bu aktivite sunum akışına teknoloji katmanı ekler. Holografik host açılış mesajı verir, sahne geçişlerini destekler ve kısa bloklarla çalışır.",
      ifm: "Ana sahnede holo gauze, LED fan veya benzeri bir teknikle uygulanır. İçerik 60-90 saniyelik bölümler halinde hazırlanır.",
      visitor: "Misafir klasik sunucu akışından farklı bir giriş ve geçiş deneyimi görür. Teknoloji vurgusu ilk dakikada hissedilir.",
      media: "Sosyal medyada hızlı tüketilen kısa klipler için uygundur. Açılışın teknoloji tarafını görünür hale getirir.",
      ops: "Sahne ışık kontrolü, açı yönetimi, önceden hazırlanmış metin ve teknik failover planı gerekir."
    },
    {
      id: "A06",
      group: "hero",
      title: "Architectural Laser Show",
      short: "Cephe çizgilerini ve plaza aksını lazer katmanıyla açılış finaline bağlayan dış mekan gösterisi.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A06-architectural-laser-show.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=KE89-HOdEKY"],
      summary: "Bu aktivite bina mimarisini lazerle okunur hale getirir. Gösteri mapping ya da drone finaline köprü görevi görebilir.",
      ifm: "Dış cephe, plaza ve karşı bina aksları kullanılarak çok noktadan kurulur. Logo veya finans çizgileri lazer ile basit ve net verilir.",
      visitor: "Misafir yapının kendisinin show'un parçası haline geldiğini görür. Özellikle gece atmosferinde premium etki verir.",
      media: "Geniş açı video ve resmi fotoğraf için güçlüdür. Mimariyi dramatize ettiği için aftermovie dilini büyütür.",
      ops: "Lazer güvenliği, beam yönleri, yansıma kontrolü, sis desteği ve resmi güvenlik prosedürleri gerekir."
    },
    {
      id: "A07",
      group: "arrival",
      title: "Mirror Arrival Tunnel",
      short: "VIP girişte aynalı yüzeyler ve ışık çizgileriyle kurulan premium karşılama tüneli.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A07-mirror-arrival-tunnel.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=8VwJMw_fLvI"],
      summary: "Bu aktivite VIP girişini sıradan karşılama alanından çıkarır. Misafirler ışıklı ve aynalı bir geçişten yürüyerek ana alana alınır.",
      ifm: "Giriş aksında 12-20 metrelik modüler bir tünel olarak kurulabilir. Metal, ayna ve kontrollü LED çizgileriyle premium dil korunur.",
      visitor: "İlk temas anı daha fotojenik hale gelir. İçeri girmeden önce özel bir davet hissi oluşur.",
      media: "Kırmızı halı yerine daha modern arrival görüntüsü üretir. Influencer giriş içerikleri için kuvvetli bir fon oluşturur.",
      ops: "Sirkülasyon genişliği, yangın çıkışı, zemin güvenliği, fotoğraf aksı ve güvenlik yönlendirmesi planlanmalıdır."
    },
    {
      id: "A08",
      group: "arrival",
      title: "Interactive Projection Floor",
      short: "Giriş veya atrium zemininde yürüdükçe tepki veren projection floor deneyimi.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A08-projection-floor.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=dRG25nRGOnY"],
      summary: "Bu aktivite zemin yüzeyini davetlinin hareketine tepki veren medya alanına dönüştürür. Adım atıldıkça ışık izi, dalga ya da marka motifi belirir.",
      ifm: "Atrium girişi, VIP yönlendirme rotası ya da geniş koridor aksında çalıştırılır. Tasarım IFM'nin sade ve kurumsal diliyle tutulur.",
      visitor: "Misafir kendi hareketine tepki veren bir mekan görür. Deneyim hızlı anlaşılır ve telefonla çekmeye uygundur.",
      media: "Üstten çekim ve dikey video için etkilidir. Kalabalık akışını görsel olarak daha canlı gösterir.",
      ops: "Projeksiyon yüksekliği, sensör kalibrasyonu, ışık seviyesi, kablo güvenliği ve zemin kaymazlığı kontrol edilir."
    },
    {
      id: "A09",
      group: "arrival",
      title: "Volumetric Hologram Experience",
      short: "VIP alanda ürün, mimari veya mesajı üç boyutlu his veren holografik deneyim noktası.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A09-volumetric-hologram.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=d6MCG3S5DIA"],
      summary: "Bu aktivite misafirin kısa süre durup izlediği holografik bir bilgi ve deneyim noktasıdır. Sürekli çalışır ve host görevinden ayrışır.",
      ifm: "VIP girişte ya da protokol çevresinde konumlanır. IFM maketi, açılış mesajı veya seçilmiş marka anlatısı burada gösterilebilir.",
      visitor: "Misafir holografik objeyi etrafından izler, kısa video çeker ve etkinlik alanına geçer. Deneyim çok hızlı anlaşılır.",
      media: "Yakın plan kliplerde teknoloji etkisini iyi verir. Basın turu için kontrollü bir demo noktası sağlar.",
      ops: "Cihaz güvenliği, karanlık kontrolü, içerik renderı ve yoğunluk yönetimi doğru çözülmelidir."
    },
    {
      id: "A10",
      group: "arrival",
      title: "Projection-Mapped Arrival Portal",
      short: "VIP giriş aksında hareketli ışık ve mapping ile kurulan büyük karşılama portalı.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A10-arrival-portal.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=W3B9N4Zr5xQ"],
      summary: "Bu aktivite misafirin geçtiği kapıyı kendi başına bir show unsuruna dönüştürür. Portal yüzeyi ışık ve içerikle canlı hale gelir.",
      ifm: "VIP girişte ya da plaza içine yönelen ana aks üzerinde konumlanır. Gece kullanımı için çok güçlü, gündüz için de okunur bir versiyon hazırlanır.",
      visitor: "Misafir ilk geçiş noktasında etkinliğin ölçeğini hisseder. Fotoğraf ve giriş videosu için kontrollü bir sahne sunar.",
      media: "Karşılama anını sıradan protokolden ayırır. Haber görüntülerinde açılışın premium seviyesi ilk saniyede anlaşılır.",
      ops: "Portal taşıyıcısı, yüzey kalitesi, içerik cue'su ve kalabalık akışı aynı plan içinde çözülmelidir."
    },
    {
      id: "A11",
      group: "arrival",
      title: "Holographic Welcome Totem",
      short: "VIP karşılama aksında kısa bilgi ve etkileşim veren dikey holografik totem.",
      impact: "Orta-Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A11-holographic-totem.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=E6r7mvXLnMw"],
      summary: "Bu aktivite giriş aksına fiziksel signage yerine teknolojik bir karşılama objesi yerleştirir. Marka mesajı, logo veya yönlendirme burada verilir.",
      ifm: "Protokol girişi, lounge yakını ya da plaza girişindeki daralmayan bir noktaya yerleşir. Tek ya da çift totem olarak kullanılabilir.",
      visitor: "Misafir girişte statik pano yerine canlı, ışıklı ve daha prestijli bir obje görür. Kısa video çekimi üretir.",
      media: "Yakın plan sosyal medya içeriği için uygundur. Teknoloji algısını girişte destekler.",
      ops: "Gün ışığı, ekran açısı, enerji beslemesi ve cihaz güvenliği dikkate alınmalıdır."
    },
    {
      id: "A12",
      group: "arrival",
      title: "Light Veil Corridor",
      short: "Yürüyüş aksında hafif sis ve dikey ışık çizgileriyle kurulan zarif geçiş koridoru.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A12-light-veil-corridor.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=v3lIyGFpcuc"],
      summary: "Bu aktivite arrival deneyimini daha sakin ve lüks bir çizgiye taşır. Sert tünel yerine daha hafif, hava gibi bir ışık koridoru kurulur.",
      ifm: "VIP yürüyüş rotasında veya mağaza koridorunda kurulur. İnce sis, düşük yoğunluklu ışık ve kontrollü refleksiyonla çalışır.",
      visitor: "Misafir yürürken ışığın içinden geçiyormuş hissi alır. Etki yüksek ama bağırmayan bir giriş deneyimidir.",
      media: "Moda ve cemiyet kitlesi için fotojenik bir arrival dili üretir. Portrait çekimlerde çok temiz görünür.",
      ops: "Sis yoğunluğu, klima etkisi, yangın alarmı uyumu ve geçiş genişliği dikkat ister."
    },
    {
      id: "A13",
      group: "immersive",
      title: "Digital River Flows",
      short: "Zemin veya plaza hattında akan dijital nehir etkisi yaratan projection deneyimi.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A13-digital-river-flows.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=-5im9Uh2hJg"],
      summary: "Bu aktivite IFM içinde ya da dış plazada akış hissi veren dijital bir rota kurar. Projection, ışık ve ses aynı kurguya bağlanır.",
      ifm: "Geniş yürüyüş aksı veya plaza zemini seçilir. Görsel dil finans akışı ve İstanbul su bağlantısı fikrini sade biçimde taşır.",
      visitor: "Misafir dijital akışın içinden veya yanından yürür. Dekor değil, mekanın parçası gibi algılanır.",
      media: "Hareketli zemin görüntüsü sosyal medyada iyi çalışır. Aftermovie'de geçiş planı olarak kullanışlıdır.",
      ops: "Parlaklık, projeksiyon yüzeyi, sis opsiyonu ve yürüme güvenliği beraber düşünülmelidir."
    },
    {
      id: "A14",
      group: "immersive",
      title: "Interactive Light Forest",
      short: "Koridor veya atrium kenarında harekete tepki veren ışık çubuklarından oluşan enstalasyon.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A14-interactive-light-forest.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=8Nj2O60BJdk"],
      summary: "Bu aktivite misafirin içinden geçebildiği veya kenarından yürüdüğü ışıklı bir enstalasyon alanı kurar. Dikey çizgiler yumuşak tepki verir.",
      ifm: "Atrium kenarı veya geniş koridor hattında 20-40 metrelik modüler bir sistem olarak kurulur. Kalabalık akışını bozmadan çalışır.",
      visitor: "Misafir yürüdükçe ışıklar canlanır. Hızlı anlaşılan, sessiz ama güçlü bir deneyim verir.",
      media: "Düşük ışıkta çok temiz premium görüntü üretir. Influencer yürüyüş çekimleri için uygundur.",
      ops: "Elektrik dağıtımı, sabitleme, sensör ayarı ve yangın geçiş boşlukları çözülmelidir."
    },
    {
      id: "A15",
      group: "immersive",
      title: "Kinetic Sculpture Plaza",
      short: "Dış plaza veya atriumda yavaş hareket eden ışıklı heykelle kurulan imza enstalasyon.",
      impact: "Yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A15-kinetic-sculpture-plaza.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=8-hxsm8lDps"],
      summary: "Bu aktivite açılış alanına hareket eden bir sanat objesi yerleştirir. Gösteri gibi değil, mekanın imza parçası gibi çalışır.",
      ifm: "Atrium boşluğu veya dış plaza merkezinde güvenli mesafe ile kurulur. Açılış saatinde özel koreografi, gün içinde sakin mod çalışır.",
      visitor: "Misafir objenin yanında durur, izler ve fotoğraf çeker. Daha yavaş ama üst segment bir deneyim hissi verir.",
      media: "Mimarlık ve etkinlik basınında güçlü görsel değer üretir. Açılışa sanat objesi niteliği katar.",
      ops: "Mühendislik hesabı, mekanik güvenlik, bakım erişimi, sigorta ve çevre bariyeri gerekir."
    },
    {
      id: "A16",
      group: "immersive",
      title: "Water Screen Projection",
      short: "Su perdesi veya sis ekranı üzerinde beliren video, ışık ve logo gösterisi.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A16-water-screen-projection.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=mSnMGw462Vk"],
      summary: "Bu aktivite klasik LED yerine su veya sis yüzeyinde görüntü gösterir. Açılış mesajı fiziksel olmayan bir yüzeyde belirir.",
      ifm: "Dış alanda rüzgar uygunsa su perdesi, iç mekanda daha kontrollü bir sis ekranı olarak kurgulanabilir. Kısa show veya geçiş noktası olabilir.",
      visitor: "Misafir görüntünün havada asılıymış gibi belirdiğini görür. Etkiyi anlaması hızlıdır.",
      media: "Yakın plan ve ağır çekimde çok etkileyicidir. Basın dilinde kolay anlatılan teknolojik bir modüldür.",
      ops: "Rüzgar, drenaj, nem, lazer güvenliği ve zeminin korunması birlikte çözülmelidir."
    },
    {
      id: "A17",
      group: "immersive",
      title: "Suspended Light Cloud",
      short: "Atrium tavanında yüzen ışık kümeleriyle kurulan sakin ama yüksek algılı enstalasyon.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A17-suspended-light-cloud.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=cYCvDcNb2Nk"],
      summary: "Bu aktivite atriuma kalıcıya yakın bir değer katar. Tavanda yüzen ışık kümeleri gün içinde de show sonrasında da yaşayabilir.",
      ifm: "Tavan taşıyıcısı uygun olan atrium veya geniş iç boşlukta kurulur. Açılışta kısa bir canlanma sekansı çalıştırılır.",
      visitor: "Misafir show anı dışında da etkileyici bir mekan objesi görür. Lüks ama sakin bir etki yaratır.",
      media: "Mimari çekimlerde çok temiz görünür. Açılışın sadece sahne değil mekan tasarımına da yatırım yaptığını hissettirir.",
      ops: "Rigging, bakım erişimi, temizlik planı ve yangın güvenliği onayı gerekir."
    },
    {
      id: "A18",
      group: "immersive",
      title: "Generative Media Art Wall",
      short: "Cephe veya büyük duvar yüzeyinde çalışan data-driven medya sanat duvarı.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A18-generative-media-wall.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=ghQpl1V4Zeg"],
      summary: "Bu aktivite büyük bir duvarı ya da medya yüzeyini açılış için yaşayan sanat yüzeyine çevirir. İçerik veri akışı, ışık ve ritim üzerinden ilerler.",
      ifm: "Mağaza cephesi, medya duvarı veya büyük geçiş duvarında uygulanır. Açılış gecesi özel loop, devamında daha sakin kurumsal loop kullanılabilir.",
      visitor: "Misafir tek noktada durup izleyebileceği güçlü bir dijital sanat yüzeyi görür. Fazla karmaşık olmadan değer hissi üretir.",
      media: "Marka ve mekanı aynı karede birleştiren güçlü görseller verir. Basın metninde medya sanat işi olarak anlatılabilir.",
      ops: "İçerik üretim süresi, ekran/projeksiyon çözünürlüğü, loop yönetimi ve çevresel ışık dikkate alınmalıdır."
    },
    {
      id: "A19",
      group: "moving",
      title: "Light Parade",
      short: "AVM içinde rota izleyen LED kostümlü performans ekibiyle hareketli gösteri akışı.",
      impact: "Orta-Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A19-light-parade.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=n2UOg67p9LM"],
      summary: "Bu aktivite sabit sahne dışında AVM içine yayılan performans üretir. Ekip belirli saatlerde rota yürür ve kısa durak show'ları yapar.",
      ifm: "Atrium, mağaza koridorları ve dış plaza arasında 15-20 dakikalık rotalar planlanır. Ana sahneye akış taşımak için kullanılabilir.",
      visitor: "Misafir beklemediği anda canlı bir performansla karşılaşır. Ekibi takip ederek ana alana yönlenebilir.",
      media: "Story formatında sürekli içerik üretir. Mekanın farklı noktalarının görünmesini sağlar.",
      ops: "Rota genişliği, güvenlik eşliği, kostüm bataryası ve kalabalık akışı planı gerekir."
    },
    {
      id: "A20",
      group: "moving",
      title: "LED Dancers",
      short: "Programlanabilir LED kostümlerle yapılan kısa koreografili dans performansı.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A20-led-dancers.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=IR84C6ah6vc"],
      summary: "Bu aktivite 4-8 dansçıyla yapılan ışıklı koreografi performansıdır. Müzik ve kostüm ışıkları aynı kurguda çalışır.",
      ifm: "Kurdele sonrası, DJ öncesi veya kısa yükseltici bir blok olarak kullanılabilir. Renkler IFM görsel diliyle programlanır.",
      visitor: "Misafir hızlı ve enerjik bir sahne anı izler. Telefonla çekmeye çok uygundur.",
      media: "Kısa reels ve story formatına doğal uyum sağlar. Açılış filminde dinamik bir ara katman olarak kullanılabilir.",
      ops: "Koreografi provası, batarya yönetimi, sahne zemini ve kulis planı gerekir."
    },
    {
      id: "A21",
      group: "moving",
      title: "Flying Musicians / Floating Orchestra",
      short: "Canlı müzik ile aerial sahnelemeyi birleştiren askılı özel performans anı.",
      impact: "Çok yüksek",
      difficulty: "Yüksek",
      image: "assets/generated/A21-floating-orchestra.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=Bc0VO8sq8dw"],
      summary: "Bu aktivite canlı müzik ile aerial performansı bir araya getirir. Müzisyen veya solist yukarıda sahnelenir ve çok özel bir an yaratır.",
      ifm: "Atrium yüksekliği uygunsa gerçek askı sistemiyle, değilse yükseltilmiş platform ve ışık destekli versiyonla uygulanabilir.",
      visitor: "Misafir mekana yukarıdan yayılan müzik ve performansı izler. Gösteri zarif ve VIP kitleye uygun kalır.",
      media: "İç mekanda çok güçlü tek kare üretir. Müzik, mimari ve performansı aynı görüntüde birleştirir.",
      ops: "Rigging mühendisliği, sigorta, prova, sanatçı güvenliği ve acil durum planı kritik konulardır."
    },
    {
      id: "A22",
      group: "moving",
      title: "LED Percussion Procession",
      short: "Işıklı vurmalı çalgılarla rota gezen ritim ekibi ve kısa durak performansları.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A22-led-percussion.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=5CwAXpEi6tA"],
      summary: "Bu aktivite klasik bando yerine daha çağdaş ve görsel bir ritim kurgusu sunar. LED vurmalı ekibi yürüyüş ve durak performanslarını birleştirir.",
      ifm: "Giriş alanı, plaza ve atrium hattında hareketli akış yaratmak için uygundur. Açılış saati öncesi atmosfer kurar.",
      visitor: "Misafir ritmi hem duyar hem görür. Enerjiyi yükseltirken AVM içinde yönlendirme de yapar.",
      media: "Sosyal video ve canlı hikaye formatında dikkat çeker. Kalabalığı hareketli gösterir.",
      ops: "Ses seviyesi, rota güvenliği, performer senkronu ve kısa set planı hazırlanmalıdır."
    },
    {
      id: "A23",
      group: "moving",
      title: "Synchronized LED Wristband Finale",
      short: "Seçili davetlilerin bilek ışıklarıyla final gösterisine dahil olduğu toplu ışık anı.",
      impact: "Yüksek",
      difficulty: "Orta-Yüksek",
      image: "assets/generated/A23-led-wristband-finale.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=lqZT095bAz0"],
      summary: "Bu aktivite finali izleyen seçili kitleyi gösterinin parçası yapar. Bileklikler müzik ve sahne cue'suyla senkron yanar.",
      ifm: "VIP alanı veya finale davet edilen izleyici grubunda uygulanır. Drone ya da ana sahne finaline eşlik eden ikinci katman olarak çalışır.",
      visitor: "Misafir sadece izleyen kişi değil, finale katılan kişinin parçası olur. Davet deneyimini daha özel hissettirir.",
      media: "Kalabalığın bir anda ışığa dönüşmesi güçlü bir final görüntüsü üretir. Kuş bakışı ve geniş açı için değerlidir.",
      ops: "Bileklik dağıtımı, toplama planı, senkron kontrolü ve yedek cihaz yönetimi gerekir."
    },
    {
      id: "A24",
      group: "moving",
      title: "Laser Harp Performance",
      short: "Lazer teller üzerinden çalınan enstrüman ve ışık performansını birleştiren sahne modülü.",
      impact: "Yüksek",
      difficulty: "Orta",
      image: "assets/generated/A24-laser-harp-performance.jpg",
      video: ["Video Referansı", "https://www.youtube.com/watch?v=euytMaRh8HM"],
      summary: "Bu aktivite canlı performans ile lazer görselliğini tek show içinde birleştirir. Kısa sahne segmenti olarak güçlü bir fark yaratır.",
      ifm: "Ana sahne, atrium demo alanı veya gala akışında tek başına kısa blok olarak kullanılabilir. DJ ve canlı performans arasına iyi oturur.",
      visitor: "Misafir hem müzikal hem görsel olarak dikkat çeken bir performans izler. Hızlı anlaşılır ve paylaşılır.",
      media: "Yakın plan ve dikey video için çok uygundur. Açılışta teknoloji ve performansı tek karede toplar.",
      ops: "Lazer güvenliği, sahne açısı, sanatçı yerleşimi ve sis yoğunluğu dikkatle yönetilmelidir."
    }
  ]
};
